services:
  - name: postgres
    type: web
    env: docker
    plan: free
    docker:
      image: postgres:latest
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres_password
      - key: POSTGRES_DB
        value: postgres

  - name: redis
    type: web
    env: docker
    plan: free
    docker:
      image: redis:latest

  - name: my-app
    type: web
    env: docker
    plan: free
    buildCommand: docker build -t my-app:latest .
    startCommand: docker run -p 80:80 my-app:latest
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: postgres_password
      - key: PGDATABASE
        value: postgres
      - key: PGHOST
        value: postgres
      - key: PGPORT
        value: 5432