services:
  - name: client
    type: web
    env: docker
    plan: free
    image: anishalx/multi-client:latest
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: http://server:5000
    port: 3000

  - name: server
    type: web
    env: docker
    plan: free
    image: anishalx/multi-server:latest
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:[YOUR_PASSWORD]@postgres:5432/mydb
      - key: REDIS_URL
        value: redis://redis:6379
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: [YOUR_PASSWORD]
      - key: PGDATABASE
        value: mydb
      - key: PGHOST
        value: postgres
      - key: PGPORT
        value: 5432
    port: 5000

  - name: worker
    type: web
    env: docker
    plan: free
    image: anishalx/multi-worker:latest
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379

  - name: nginx
    type: web
    env: docker
    plan: free
    image: anishalx/multi-nginx:latest
    startCommand: docker run -p 80:80 anishalx/multi-nginx
    ports:
      - 80

  - name: postgres
    type: postgres
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: [YOUR_PASSWORD]
      - key: POSTGRES_DB
        value: mydb

  - name: redis
    type: redis
    plan: free
    ports:
      - 6379
